// Re-export barrel — all AI functions live in ./functions/
export { setAiWeights } from './functions/set-ai-weights';
export { getAiWeights } from './functions/get-ai-weights';
export { resetAiWeights } from './functions/reset-ai-weights';
export type { AiDifficulty } from './functions/ai-difficulty';
export { setAiDifficulty } from './functions/set-ai-difficulty';
export { battleWinProb } from './functions/battle-win-prob';
export { attackBaseOf } from './functions/attack-base-of';
export { defenseBaseOf } from './functions/defense-base-of';
export { minTroopsToConquer } from './functions/min-troops-to-conquer';
export { survivorsAfterWin } from './functions/survivors-after-win';
export { recruitRate } from './functions/recruit-rate';
export { playerStrength } from './functions/player-strength';
export { holdProbability } from './functions/hold-probability';
export { immediateFallProb } from './functions/immediate-fall-prob';
export { planetValue } from './functions/planet-value';
export type { AttackPlan } from './functions/evaluate-attacks';
export { evaluateAttacks } from './functions/evaluate-attacks';
export { bestAttackNow } from './functions/best-attack-now';
export type { BuildCandidate } from './functions/build-candidates';
export { buildCandidates } from './functions/build-candidates';
export { buildingWorth } from './functions/building-worth';
export type { StrategyKind, Plan } from './functions/plan-types';
export { planFor } from './functions/plan-for';
export { denialValue } from './functions/denial-value';
export { mastermindDraftPick } from './functions/mastermind-draft-pick';
export { influencePlay } from './functions/influence-play';
export type { MastermindDecision } from './functions/mastermind-action';
export { mastermindAction } from './functions/mastermind-action';
export { mastermindEvaluateTrade } from './functions/mastermind-evaluate-trade';
